### ISSUE TITLE
Does the todo supports remote data storage in the future？

### ISSUE THREAD

**Issue by chenxofhit** [ubeydeozdmr/vue-todo-app#3]
Thanks for your excellent work. I find the UI well-designed and neatly.  If the todo supports remote data storage, it will be better in my opinion.

**Comment by ubeydeozdmr** [comment]
> Thanks for your excellent work. I find the UI well-designed and neatly. If the todo supports remote data storage, it will be better in my opinion.

This year or next year, I am making a todo application using database instead of localStorage and planning it on another repo. I totally made use of tailwindcss on the UI side

By the way, thanks a lot for your comment and sorry for my very late reply, I just noticed the issue.
